#!/usr/bin/env bash

eval $(docker-machine env -u)

mkdir -p $HOME/.ansible
mkdir -p $HOME/.ssh
touch $HOME/.ssh/config
touch $HOME/.ssh/known_hosts
echo docker pull metalguardian/ansible

arguments="$@"
docker run \
    --rm \
    -ti \
    --env TERM=${TERM} \
    --env SSH_AUTH_SOCK=/ssh-agent \
    --env ANSIBLE_SSH_ARGS \
    --user=`id -u`:`id -g` \
    --init \
    --net host \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v ${HOME}/.ansible:${HOME}/.ansible \
    -v ${HOME}/.ssh/config:${HOME}/.ssh/config \
    -v ${HOME}/.ssh/known_hosts:${HOME}/.ssh/known_hosts \
    -v $(pwd):$(pwd) -w $(pwd) \
    -v $SSH_AUTH_SOCK:/ssh-agent \
    metalguardian/ansible \
    ansible-playbook \
    ${arguments}